name: Trigger Hub Update
on:
  push:
    branches:
      - main

jobs:
  Trigger-Hub-Update:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Hub Update
        uses: cephalofair-games-llc/rules-hub-actions/trigger-hub@v1.0
        with:
          pat: ${{ secrets.PAT }}
